### ISSUE TITLE
【need_help】def generate(%Protobuf.Protoc.Context{} = ctx, %Google.Protobuf.FileDescriptorProto{} = desc, plugins)

### ISSUE THREAD

**Issue by openmindw** [drowzy/protobuf_generate#5]
env:
Erlang/OTP 26 [erts-14.2.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Mix 1.16.3 (compiled with Erlang/OTP 24)

wsl2-arch

-------------------------------------
when i use the commad:  mix protobuf.generate --output-path=./lib --include-path=./priv/protos helloworld.proto it will report:

`
# mix protobuf.generate --output-path=./lib --include-path=./priv/protos helloworld.proto
==> protobuf_generate
Compiling 9 files (.ex)
Generated protobuf_generate app
==> elixir_grpc
Generated elixir_grpc app
** (FunctionClauseError) no function clause matching in ProtobufGenerate.CodeGen.generate/3

    The following arguments were given to ProtobufGenerate.CodeGen.generate/3:

        # 1
        %Protobuf.Protoc.Context{plugins: [], global_type_mapping: %{"helloworld.proto" => %{".helloworld.HelloReply" => %{type_name: "Helloworld.HelloReply"}, ".helloworld.HelloRequest" => %{type_name: "Helloworld.HelloRequest"}}}, package: nil, package_prefix: nil, module_prefix: nil, syntax: nil, dep_type_mapping: %{}, namespace: [], gen_descriptors?: false, transform_module: nil, one_file_per_module?: false, include_docs?: false, custom_file_options: %{}}

        # 2
        nil

        # 3
        [ProtobufGenerate.Plugins.Enum, ProtobufGenerate.Plugins.Extension, ProtobufGenerate.Plugins.Message]

    Attempted function clauses (showing 1 out of 1):

        def generate(%Protobuf.Protoc.Context{} = ctx, %Google.Protobuf.FileDescriptorProto{} = desc, plugins)

    (protobuf_generate 0.1.2) lib/protobuf_generate/code_gen.ex:8: ProtobufGenerate.CodeGen.generate/3
    (elixir 1.16.3) lib/enum.ex:4326: Enum.flat_map_list/2
    (protobuf_generate 0.1.2) lib/mix/protobuf.generate.ex:124: Mix.Tasks.Protobuf.Generate.generate/2
    (protobuf_generate 0.1.2) lib/mix/protobuf.generate.ex:86: Mix.Tasks.Protobuf.Generate.run/1
    (mix 1.16.3) lib/mix/task.ex:478: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.16.3) lib/mix/cli.ex:96: Mix.CLI.run_task/2
    /root/.local/share/mise/installs/elixir/1.16.3/bin/mix:2: (file)

`

the helloword file code:
`
syntax = "proto3";

package helloworld;

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greeting
message HelloReply {
  string message = 1;
}

// The greeting service definition.
service Greeter {
  // Greeting function
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

`

**Comment by openmindw** [comment]
"protobuf_generate": {:hex, :protobuf_generate, "0.1.2", "45b9a9ae8606333cdea993ceaaecd799d206cdfe23348d37c06207eac76cbee6", [:mix], [{:protobuf, "~> 0.12", [hex: :protobuf, repo: "hexpm", optional: false]}], "hexpm", "55b0ff8385703317ca90e1bd30a2ece99e80ae0c73e6ebcfb374e84e57870d61"},

**Comment by drowzy** [comment]
Try: `mix protobuf.generate --output-path=./lib --include-path=./priv/protos./priv/protos/test.proto`

**Comment by bcardarella** [comment]
I'm getting this same error. Both on the release 1.3 and on `main`.

I have the following:

```proto
syntax = "proto3";

package element;

// Element represents an HTML-like element with a tag name, attributes, and child elements
message Element {
  // The tag name of the element (e.g., "div", "span", "p")
  string tag_name = 1;
  
  // A map of attributes where both keys and values are strings
  map<string, string> attributes = 2;
  
  // Each element can have zero or more children that are also elements
  repeated Element children = 3;
  
  // Optional: Text content contained within the element
  string text_content = 4;
}
```

My proto file is at `priv/protos/element.proto`

I ran: `mix protobuf.generate --output-path=./lib --include-path=./priv/protos element.proto`


And I get:

```
** (FunctionClauseError) no function clause matching in ProtobufGenerate.CodeGen.generate/3    
    
    The following arguments were given to ProtobufGenerate.CodeGen.generate/3:
    
        # 1
        %Protobuf.Protoc.Context{plugins: [], comments: %{}, global_type_mapping: %{"element.proto" => %{".element.Element" => %{type_name: "Element.Element"}, ".element.Element.AttributesEntry" => 
%{type_name: "Element.Element.AttributesEntry"}}}, package: nil, package_prefix: nil, module_prefix: nil, syntax: nil, dep_type_mapping: %{}, namespace: [], gen_descriptors?: false, transform_module
: nil, one_file_per_module?: false, include_docs?: false, custom_file_options: %{}, current_comment_path: ""}
    
        # 2
        nil
    
        # 3
        [ProtobufGenerate.Plugins.Enum, ProtobufGenerate.Plugins.Extension, ProtobufGenerate.Plugins.Message]
    
    Attempted function clauses (showing 1 out of 1):
    
        def generate(%Protobuf.Protoc.Context{} = ctx, %Google.Protobuf.FileDescriptorProto{} = desc, plugins)
    
    (protobuf_generate 0.1.3) lib/protobuf_generate/code_gen.ex:8: ProtobufGenerate.CodeGen.generate/3
    (elixir 1.18.0) lib/enum.ex:4438: Enum.flat_map_list/2
    (protobuf_generate 0.1.3) lib/mix/protobuf.generate.ex:124: Mix.Tasks.Protobuf.Generate.generate/2
    (protobuf_generate 0.1.3) lib/mix/protobuf.generate.ex:86: Mix.Tasks.Protobuf.Generate.run/1
    (mix 1.18.0) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.18.0) lib/mix/cli.ex:107: Mix.CLI.run_task/2
    /Users/bcardarella/.asdf/installs/elixir/1.18.0/bin/mix:2: (file)

```

**Comment by bcardarella** [comment]
I found what is causing the issue.

If you pass the `--include-path=` as the base path for the protofiles, the a file name after as the README tells you to do, the file will be relative to that include path. For example, if you do `--include-path=./foo/bar user.proto` the `request.file_to_generate` will be `["../../user.proto"]` then it will never match here https://github.com/drowzy/protobuf_generate/blob/main/lib/mix/protobuf.generate.ex#L125 and the `desc` will be `nil` and the mix task fails.

I think the issue is that the tests themselves are joining the proto file with the tmp_dir: https://github.com/drowzy/protobuf_generate/blob/main/test/mix/tasks/protobuf.generate_test.exs#L13 and it shouldn't be doing that. The test tasks get run as: 

`mix protobuf.generate --include-path={tmp_dir} --output-path={tmp_dir} {tmp_dir}/user.proto`

and it *should* be run as:

`mix protobuf.generate --include-path={tmp_dir} --output-path={tmp_dir} user.proto`

**Comment by aseigo** [comment]
Following the [documentation for http transcoding](https://hexdocs.pm/grpc/readme.html#http-transcoding) in the `grpc` module, I was getting the same errors. This only started happening once there were multiple include paths provided, but that really was a bit of a red herring: the generation was working with just one include path almost by accident as I was also passing in the full path to the proto file which would then match on the check for the relative path being the file path.

Anyways, the above PR fixes this for my use case and I believe this to be more correct in any case. If anyone else can verify that would be fantastic!

I am left wondering how the http transcoding documentation was ever working, however... :/
